[package]
name = "demo"
version = "0.1.0"
authors = ["salamer <gagasalamer@163.com>"]
edition = "2018"

[dependencies]
hora = { package = "hora", path = "../", features=["simd"]}
hdf5 = {version = "0.7.1"}
rayon = "^1.5"
rand = "0.8.4"
rand_distr = "0.4.1"